usethis::use_build_ignore("devtools_history.R")
usethis::use_package("shiny")
usethis::use_package("dplyr")
usethis::use_package("ggplot2")
usethis::use_package("sortable")
usethis::use_package("shinyjs")
usethis::use_package("stringr")
usethis::use_package("rlang")
usethis::use_package("colourpicker")

