project:
  type: website
  output-dir: ..
website:
  title: "VisualizeR Documentation"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: getting-started.qmd
        text: "Getting Started"
      - href: reference.qmd
        text: "Function Reference"
