project:
  type: website
  output-dir: ..
website:
  title: "VisualizeR Documentation"
  site-url: https://albamqs.github.io/visualizer/
  repo-url: https://github.com/AlbaMqs/visualizer
  issue-url: https://github.com/AlbaMqs/visualizer/issues/new/choose
  repo-actions: [edit, issue]
  search:
    show-item-context: true
    type: overlay
  page-footer:
    left: &copy; 2024 [Alba Maiques](https://github.com/AlbaMqs). Licensed under the [MIT License](https://opensource.org/licenses/MIT).

    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: https://github.com/AlbaMqs/visualizer/blob/main/LICENSE.md
    right:
      - icon: github
        href: https://github.com/AlbaMqs/visualizer
        aria-label: VisualizeR GitHub
  page-navigation: true
  sidebar:
    style: "floating"
    collapse-level: 2
    align: left
    contents:
      - href: index.qmd
        text: "Home"
      - href: getting-started.qmd
        text: "Getting Started"
      - href: reference.qmd
        text: "Function Reference"

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
