project:
  type: website
  output-dir: ..
website:
  title: "VisualizeR Documentation"
  site-url: https://albamqs.github.io/visualizer/
  repo-url: https://github.com/AlbaMqs/visualizer
  issue-url: https://github.com/AlbaMqs/visualizer/issues/new/choose
  repo-actions: [edit, issue]
  search:
    show-item-context: true
    type: overlay
  page-footer:
    left: |
      Proudly supported by
      [![](https://posit.co/wp-content/uploads/2024/06/Posit-Logos-2024_horiz-full-color.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: https://github.com/AlbaMqs/visualizer/blob/main/LICENSE.md
    right:
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: VisualizeR GitHub
  page-navigation: true
  sidebar:
    style: "floating"
    collapse-level: 2
    align: left
    left:
      - href: index.qmd
        text: "Home"
      - href: getting-started.qmd
        text: "Getting Started"
      - href: reference.qmd
        text: "Function Reference"

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
